### PR TITLE
Asg3

### PR DESCRIPTION
**Pull request by zohaib-c**
This pull request is created for the collaborators invited to **review** our code which does not require merging the pull request.

### CODE REVIEW

**Review by Simon946 — COMMENTED** [review]
Good luck on the assignment!

**Review by cgs980 — COMMENTED** [review]
The code is well-structured and easy to read, but it could benefit from additional error handling to ensure proper behavior in unexpected scenarios.

**Review by davidbukva — COMMENTED** [review]
There are no comments, adding some would help with understanding the structure of the code at some points.

**Review by galacado — COMMENTED** [review]
Overall the code is very understandable, the structure is well thought out and the naming is descriptive and clear. The use of the command design pattern is a great addition. It would be good to add a few additional comments to explain some parts and their functions. Other than that most of the other commenters mentioned the other drawbacks, so I have mostly positive feedback.

**Review by Zakadh — COMMENTED** [review]
Overall very clear and consise code. Good use of try and catch statements for error handling and functions only perform one task each. However, I do notice a few improvement points: Using more comments, some code does not speak for itsself and requires comments to be clear and readable. Also, some function & variable names do not give enough information. Make sure to name the functions and variables as clear as possible

**Review by EmilChoparinov — CHANGES_REQUESTED** [review]
Overall the code is of decent quality although the git repo is in a poor state. Cleanup the repo with this [.gitignore generated with gitignore.io](https://www.toptal.com/developers/gitignore/api/java,gradle,macos,windows,linux,sonar). It should be enough to fix all your repos issues as long as you add an extra line to ignore the build folder as well.

Great work!

**Pull request merged**
